# Generated by Django 4.2.7 on 2026-02-07 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0001_initial"),
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryHealthReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_date", models.DateField(auto_now_add=True, db_index=True)),
                ("total_items_stocked", models.PositiveIntegerField(default=0)),
                ("low_stock_items", models.PositiveIntegerField(default=0)),
                ("overstock_items", models.PositiveIntegerField(default=0)),
                ("dead_stock_items", models.PositiveIntegerField(default=0)),
                (
                    "total_inventory_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "inventory_turnover_ratio",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "storage_utilization",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "forecast_accuracy",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_health",
                        to="inventory.store",
                    ),
                ),
            ],
            options={
                "ordering": ["-report_date"],
            },
        ),
        migrations.CreateModel(
            name="BusinessInsights",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("insight_date", models.DateField(auto_now_add=True, db_index=True)),
                (
                    "insight_type",
                    models.CharField(
                        choices=[
                            ("DEMAND", "Demand Trend"),
                            ("INVENTORY", "Inventory Issue"),
                            ("PRICING", "Pricing Opportunity"),
                            ("SALES", "Sales Pattern"),
                            ("ANOMALY", "Anomaly Detection"),
                            ("RECOMMENDATION", "Recommendation"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("recommendation", models.TextField(blank=True)),
                (
                    "confidence_score",
                    models.DecimalField(decimal_places=2, default=0.8, max_digits=3),
                ),
                (
                    "impact_score",
                    models.DecimalField(decimal_places=2, default=0.5, max_digits=3),
                ),
                ("is_actioned", models.BooleanField(default=False)),
                ("action_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insights",
                        to="inventory.store",
                    ),
                ),
            ],
            options={
                "ordering": ["-insight_date"],
            },
        ),
        migrations.CreateModel(
            name="ProductSalesAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("quantity_sold", models.PositiveIntegerField(default=0)),
                (
                    "revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "profit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "average_rating",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                ("customer_reviews", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales_analytics",
                        to="products.product",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_analytics",
                        to="inventory.store",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("product", "store", "date")},
            },
        ),
        migrations.CreateModel(
            name="DemandForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("forecast_date", models.DateField(db_index=True)),
                (
                    "forecasted_demand",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "confidence_level",
                    models.DecimalField(decimal_places=2, default=0.85, max_digits=3),
                ),
                ("model_used", models.CharField(default="ARIMA", max_length=100)),
                (
                    "actual_demand",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "accuracy",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forecasts",
                        to="products.product",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forecasts",
                        to="inventory.store",
                    ),
                ),
            ],
            options={
                "ordering": ["-forecast_date"],
                "indexes": [
                    models.Index(
                        fields=["product", "store", "forecast_date"],
                        name="analytics_d_product_52bc52_idx",
                    )
                ],
                "unique_together": {("product", "store", "forecast_date")},
            },
        ),
        migrations.CreateModel(
            name="DailySalesMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "total_sales",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("total_items_sold", models.PositiveIntegerField(default=0)),
                ("total_transactions", models.PositiveIntegerField(default=0)),
                (
                    "average_transaction_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("top_products", models.JSONField(blank=True, default=list)),
                ("peak_hours", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_metrics",
                        to="inventory.store",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["store", "date"], name="analytics_d_store_i_3b2bce_idx"
                    )
                ],
                "unique_together": {("store", "date")},
            },
        ),
        migrations.CreateModel(
            name="CategoryAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("total_quantity", models.PositiveIntegerField(default=0)),
                (
                    "avg_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "profit_margin",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="products.category",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.store",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("category", "store", "date")},
            },
        ),
    ]
