# Generated by Django 4.2.7 on 2026-02-07 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DataIngestionJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_id", models.CharField(max_length=100, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("PARTIAL", "Partially Completed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("records_processed", models.PositiveIntegerField(default=0)),
                ("records_inserted", models.PositiveIntegerField(default=0)),
                ("records_updated", models.PositiveIntegerField(default=0)),
                ("records_failed", models.PositiveIntegerField(default=0)),
                ("error_log", models.TextField(blank=True)),
                ("warning_log", models.TextField(blank=True)),
                ("file_path", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="DataSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("CSV", "CSV File"),
                            ("JSON", "JSON File"),
                            ("EXCEL", "Excel File"),
                            ("API", "External API"),
                            ("DATABASE", "Database"),
                            ("POS", "POS System"),
                            ("ERP", "ERP System"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("connection_config", models.JSONField()),
                ("field_mapping", models.JSONField()),
                ("is_active", models.BooleanField(default=True)),
                ("auto_sync_enabled", models.BooleanField(default=False)),
                (
                    "sync_frequency_minutes",
                    models.PositiveIntegerField(blank=True, default=60, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ImportedDataAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=255)),
                ("record_id", models.CharField(max_length=255)),
                ("action", models.CharField(max_length=50)),
                ("before_data", models.JSONField(blank=True, null=True)),
                ("after_data", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_trail",
                        to="data_ingestion.dataingestionjob",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DataValidationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.CharField(max_length=255)),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("REQUIRED", "Required Field"),
                            ("UNIQUE", "Unique Value"),
                            ("RANGE", "Value Range"),
                            ("PATTERN", "Pattern Match"),
                            ("CUSTOM", "Custom Logic"),
                        ],
                        max_length=50,
                    ),
                ),
                ("rule_definition", models.JSONField()),
                ("error_message", models.CharField(max_length=500)),
                ("is_critical", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "data_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validation_rules",
                        to="data_ingestion.datasource",
                    ),
                ),
            ],
            options={
                "ordering": ["field_name"],
            },
        ),
        migrations.CreateModel(
            name="DataTransformationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.CharField(max_length=255)),
                ("original_value", models.TextField()),
                ("transformed_value", models.TextField()),
                ("transformation_applied", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transformation_logs",
                        to="data_ingestion.dataingestionjob",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="dataingestionjob",
            name="data_source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ingestion_jobs",
                to="data_ingestion.datasource",
            ),
        ),
    ]
