# Generated by Django 4.2.7 on 2026-02-07 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0001_initial"),
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ForecastModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("ARIMA", "ARIMA"),
                            ("LSTM", "LSTM Neural Network"),
                            ("PROPHET", "Facebook Prophet"),
                            ("ENSEMBLE", "Ensemble Model"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("parameters", models.JSONField(default=dict)),
                ("features_used", models.JSONField(default=list)),
                (
                    "mape",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "rmse",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "r_squared",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("training_data_points", models.PositiveIntegerField(default=0)),
                (
                    "training_accuracy",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "validation_accuracy",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("model_file_path", models.CharField(blank=True, max_length=500)),
                ("last_trained_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ForecastingTrainingJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("training_data_date_from", models.DateField()),
                ("training_data_date_to", models.DateField()),
                ("parameters_used", models.JSONField()),
                ("error_message", models.TextField(blank=True)),
                ("log_output", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_jobs",
                        to="ml_services.forecastmodel",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="ForecastingMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_predictions", models.PositiveIntegerField(default=0)),
                ("accurate_predictions", models.PositiveIntegerField(default=0)),
                ("overall_mape", models.DecimalField(decimal_places=2, max_digits=5)),
                ("overall_rmse", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "best_performing_category",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "worst_performing_category",
                    models.CharField(blank=True, max_length=255),
                ),
                ("last_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "model",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="ml_services.forecastmodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DemandForecastingResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("forecast_date", models.DateField()),
                ("forecast_period", models.CharField(default="DAILY", max_length=50)),
                (
                    "predicted_demand",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("lower_bound", models.DecimalField(decimal_places=2, max_digits=10)),
                ("upper_bound", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "confidence_level",
                    models.DecimalField(decimal_places=2, default=0.95, max_digits=3),
                ),
                (
                    "actual_demand",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "forecast_accuracy",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ml_services.forecastmodel",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forecast_results",
                        to="products.product",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.store",
                    ),
                ),
            ],
            options={
                "ordering": ["-forecast_date"],
                "unique_together": {("product", "store", "forecast_date", "model")},
            },
        ),
    ]
