# Generated by Django 4.2.7 on 2026-02-07 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0001_initial"),
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductDetectionModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("model_type", models.CharField(default="YOLO8", max_length=100)),
                ("description", models.TextField(blank=True)),
                ("model_file_path", models.CharField(max_length=500)),
                (
                    "confidence_threshold",
                    models.DecimalField(decimal_places=2, default=0.5, max_digits=3),
                ),
                (
                    "mAP",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "inference_time_ms",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("trained_on_categories", models.JSONField(default=list)),
                ("last_trained_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StockLevelDetectionTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_id", models.CharField(max_length=100, unique=True)),
                ("image", models.ImageField(upload_to="cv_tasks/%Y/%m/%d/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("processing_start_time", models.DateTimeField(blank=True, null=True)),
                ("processing_end_time", models.DateTimeField(blank=True, null=True)),
                ("detected_items", models.JSONField(default=dict)),
                ("confidence_scores", models.JSONField(default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cv_tasks",
                        to="inventory.store",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ShelfAnalysisResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shelf_location", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="shelf_analysis/%Y/%m/%d/")),
                ("analysis_date", models.DateTimeField(auto_now_add=True)),
                ("total_facings", models.PositiveIntegerField()),
                ("products_detected", models.JSONField(default=dict)),
                ("missing_products", models.JSONField(default=list)),
                (
                    "out_of_stock_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "shelf_quality_score",
                    models.DecimalField(decimal_places=2, max_digits=3),
                ),
                ("is_compliant_with_display_policy", models.BooleanField()),
                (
                    "confidence_average",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                ("recommendations", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ai_model_used",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cv_services.productdetectionmodel",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shelf_analysis",
                        to="inventory.store",
                    ),
                ),
            ],
            options={
                "ordering": ["-analysis_date"],
            },
        ),
        migrations.CreateModel(
            name="ProductRecognitionData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("color", models.CharField(blank=True, max_length=100)),
                ("size_category", models.CharField(blank=True, max_length=50)),
                ("packaging_material", models.CharField(blank=True, max_length=100)),
                ("reference_images", models.JSONField(default=list)),
                ("dominant_colors", models.JSONField(default=list)),
                ("texture_features", models.JSONField(default=dict)),
                ("shape_descriptor", models.CharField(blank=True, max_length=255)),
                ("is_trained", models.BooleanField(default=False)),
                ("trained_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cv_training_data",
                        to="products.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VisionAnalyticMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metric_date", models.DateField()),
                ("total_images_processed", models.PositiveIntegerField(default=0)),
                (
                    "detection_accuracy",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "average_processing_time",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "stock_visibility_accuracy",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "shelf_compliance_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("detected_anomalies", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vision_metrics",
                        to="inventory.store",
                    ),
                ),
            ],
            options={
                "ordering": ["-metric_date"],
                "unique_together": {("store", "metric_date")},
            },
        ),
    ]
